#!/usr/bin/env python3
"""
email_report.py - Send a markdown report as a styled HTML email.

Usage:
    python email_report.py <path-to-markdown-file>

Used by the Claude Code scheduled task:
  1. Claude Code does the web research (free with subscription)
  2. Saves the report as markdown
  3. Calls this script to convert to HTML and send via SMTP

Reads SMTP configuration from .env in the same directory.
"""

import smtplib
import sys
import os
import markdown
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent / ".env")

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
EMAIL_FROM = os.getenv("EMAIL_FROM") or SMTP_USER
EMAIL_TO = os.getenv("EMAIL_TO", "miriam@miriamllantada.com,ricardo@miriamllantada.com")


def to_html(md_text):
    html_body = markdown.markdown(
        md_text,
        extensions=["tables", "fenced_code", "toc"],
    )
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    max-width: 800px; margin: 0 auto; padding: 20px;
    color: #1a1a1a; line-height: 1.6;
  }}
  h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
  h2 {{ color: #2980b9; margin-top: 30px; }}
  h3 {{ color: #27ae60; }}
  table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 10px 12px; text-align: left; }}
  th {{ background-color: #3498db; color: white; }}
  tr:nth-child(even) {{ background-color: #f8f9fa; }}
  a {{ color: #2980b9; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  blockquote {{
    border-left: 4px solid #3498db; margin: 15px 0;
    padding: 10px 20px; background: #f0f7ff;
  }}
  ul, ol {{ padding-left: 24px; }}
  li {{ margin-bottom: 6px; }}
  .footer {{
    margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd;
    color: #777; font-size: 0.85em;
  }}
</style>
</head>
<body>
{html_body}
<div class="footer">
  <p>Generated by ResearchFinder | Powered by Claude Code</p>
  <p>Report date: {datetime.now().strftime("%B %d, %Y at %H:%M")}</p>
</div>
</body>
</html>"""


def send_email(subject, html_body):
    recipients = [r.strip() for r in EMAIL_TO.split(",")]

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = EMAIL_FROM
    msg["To"] = ", ".join(recipients)

    msg.attach(MIMEText("View this email in an HTML-capable client.", "plain"))
    msg.attach(MIMEText(html_body, "html"))

    print(f"  Sending to: {', '.join(recipients)}")

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(EMAIL_FROM, recipients, msg.as_string())

    print("  Email sent successfully.")


def main():
    if len(sys.argv) < 2:
        print("Usage: python email_report.py <path-to-markdown-file>", file=sys.stderr)
        sys.exit(1)

    md_path = Path(sys.argv[1])
    if not md_path.exists():
        print(f"ERROR: File not found: {md_path}", file=sys.stderr)
        sys.exit(1)

    md_text = md_path.read_text(encoding="utf-8")
    html = to_html(md_text)

    today = datetime.now().strftime("%B %d, %Y")
    subject = f"Cosmetic Ingredients Research Digest — {today}"

    # Also save the HTML version
    html_path = md_path.with_suffix(".html")
    html_path.write_text(html, encoding="utf-8")
    print(f"  Saved: {html_path}")

    send_email(subject, html)
    print("Done.")


if __name__ == "__main__":
    main()
